services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: renewables-profiles:latest
    ports:
      - "8085:8085"
    volumes:
      - /root/cutouts:/data
      - ./output:/app/output
    restart: unless-stopped
